/*
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.clientapi.forgejo.invoker;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.internal.bind.util.ISO8601Utils;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonElement;
import io.gsonfire.GsonFireBuilder;
import io.gsonfire.TypeSelector;

import okio.ByteString;

import java.io.IOException;
import java.io.StringReader;
import java.lang.reflect.Type;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.ParsePosition;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Locale;
import java.util.Map;
import java.util.HashMap;

/*
 * A JSON utility class
 *
 * NOTE: in the future, this class may be converted to static, which may break
 *       backward-compatibility
 */
public class JSON {
    private static Gson gson;
    private static boolean isLenientOnJson = false;
    private static DateTypeAdapter dateTypeAdapter = new DateTypeAdapter();
    private static SqlDateTypeAdapter sqlDateTypeAdapter = new SqlDateTypeAdapter();
    private static OffsetDateTimeTypeAdapter offsetDateTimeTypeAdapter = new OffsetDateTimeTypeAdapter();
    private static LocalDateTypeAdapter localDateTypeAdapter = new LocalDateTypeAdapter();
    private static ByteArrayAdapter byteArrayAdapter = new ByteArrayAdapter();

    @SuppressWarnings("unchecked")
    public static GsonBuilder createGson() {
        GsonFireBuilder fireBuilder = new GsonFireBuilder()
        ;
        GsonBuilder builder = fireBuilder.createGsonBuilder();
        return builder;
    }

    private static String getDiscriminatorValue(JsonElement readElement, String discriminatorField) {
        JsonElement element = readElement.getAsJsonObject().get(discriminatorField);
        if (null == element) {
            throw new IllegalArgumentException("missing discriminator field: <" + discriminatorField + ">");
        }
        return element.getAsString();
    }

    /**
     * Returns the Java class that implements the OpenAPI schema for the specified discriminator value.
     *
     * @param classByDiscriminatorValue The map of discriminator values to Java classes.
     * @param discriminatorValue The value of the OpenAPI discriminator in the input data.
     * @return The Java class that implements the OpenAPI schema
     */
    private static Class getClassByDiscriminator(Map classByDiscriminatorValue, String discriminatorValue) {
        Class clazz = (Class) classByDiscriminatorValue.get(discriminatorValue);
        if (null == clazz) {
            throw new IllegalArgumentException("cannot determine model class of name: <" + discriminatorValue + ">");
        }
        return clazz;
    }

    {
        GsonBuilder gsonBuilder = createGson();
        gsonBuilder.registerTypeAdapter(Date.class, dateTypeAdapter);
        gsonBuilder.registerTypeAdapter(java.sql.Date.class, sqlDateTypeAdapter);
        gsonBuilder.registerTypeAdapter(OffsetDateTime.class, offsetDateTimeTypeAdapter);
        gsonBuilder.registerTypeAdapter(LocalDate.class, localDateTypeAdapter);
        gsonBuilder.registerTypeAdapter(byte[].class, byteArrayAdapter);
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.APIError.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.AccessToken.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.Activity.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.ActivityPub.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.AddCollaboratorOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.AddTimeOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.AnnotatedTag.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.AnnotatedTagObject.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.Attachment.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.BlockedUser.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.Branch.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.BranchProtection.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.ChangeFileOperation.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.ChangeFilesOptions.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.ChangedFile.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.CombinedStatus.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.Comment.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.Commit.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.CommitAffectedFiles.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.CommitDateOptions.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.CommitMeta.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.CommitStats.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.CommitStatus.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.CommitUser.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.ContentsResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.CreateAccessTokenOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.CreateBranchProtectionOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.CreateBranchRepoOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.CreateEmailOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.CreateFileOptions.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.CreateForkOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.CreateGPGKeyOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.CreateHookOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.CreateIssueCommentOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.CreateIssueOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.CreateKeyOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.CreateLabelOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.CreateMilestoneOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.CreateOAuth2ApplicationOptions.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.CreateOrgOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.CreatePullRequestOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.CreatePullReviewComment.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.CreatePullReviewOptions.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.CreatePushMirrorOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.CreateReleaseOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.CreateRepoOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.CreateStatusOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.CreateTagOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.CreateTeamOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.CreateUserOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.CreateWikiPageOptions.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.Cron.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.DeleteEmailOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.DeleteFileOptions.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.DeployKey.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.DismissPullReviewOptions.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.EditAttachmentOptions.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.EditBranchProtectionOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.EditDeadlineOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.EditGitHookOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.EditHookOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.EditIssueCommentOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.EditIssueOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.EditLabelOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.EditMilestoneOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.EditOrgOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.EditPullRequestOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.EditReactionOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.EditReleaseOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.EditRepoOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.EditTeamOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.EditUserOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.Email.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.ExternalTracker.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.ExternalWiki.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.FileCommitResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.FileDeleteResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.FileLinksResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.FileResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.FilesResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.GPGKey.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.GPGKeyEmail.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.GeneralAPISettings.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.GeneralAttachmentSettings.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.GeneralRepoSettings.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.GeneralUISettings.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.GenerateRepoOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.GitBlobResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.GitEntry.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.GitHook.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.GitObject.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.GitTreeResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.GitignoreTemplateInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.Hook.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.Identity.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.InternalTracker.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.Issue.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.IssueConfig.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.IssueConfigContactLink.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.IssueConfigValidation.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.IssueDeadline.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.IssueFormField.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.IssueLabelsOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.IssueMeta.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.IssueTemplate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.Label.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.LabelTemplate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.LicenseTemplateInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.LicensesTemplateListEntry.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.MarkdownOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.MarkupOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.MergePullRequestOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.MigrateRepoOptions.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.Milestone.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.ModelPackage.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.NewIssuePinsAllowed.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.NodeInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.NodeInfoServices.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.NodeInfoSoftware.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.NodeInfoUsage.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.NodeInfoUsageUsers.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.Note.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.NotificationCount.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.NotificationSubject.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.NotificationThread.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.OAuth2Application.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.Organization.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.OrganizationPermissions.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.PRBranchInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.PackageFile.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.PayloadCommit.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.PayloadCommitVerification.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.PayloadUser.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.Permission.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.PublicKey.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.PullRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.PullRequestMeta.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.PullReview.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.PullReviewComment.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.PullReviewRequestOptions.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.PushMirror.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.Reaction.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.Reference.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.Release.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.RenameUserOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.RepoCollaboratorPermission.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.RepoCommit.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.RepoTopicOptions.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.RepoTransfer.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.Repository.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.RepositoryMeta.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.SearchResults.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.ServerVersion.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.StopWatch.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.SubmitPullReviewOptions.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.Tag.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.Team.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.TeamSearch200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.TimelineComment.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.TopicName.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.TopicResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.TrackedTime.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.TransferRepoOption.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.UpdateFileOptions.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.User.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.UserHeatmapData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.UserSearch200Response.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.UserSettings.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.UserSettingsOptions.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.WatchInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.WikiCommit.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.WikiCommitList.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.WikiPage.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.clientapi.forgejo.model.WikiPageMetaData.CustomTypeAdapterFactory());
        gson = gsonBuilder.create();
    }

    /**
     * Get Gson.
     *
     * @return Gson
     */
    public static Gson getGson() {
        return gson;
    }

    /**
     * Set Gson.
     *
     * @param gson Gson
     */
    public static void setGson(Gson gson) {
        JSON.gson = gson;
    }

    public static void setLenientOnJson(boolean lenientOnJson) {
        isLenientOnJson = lenientOnJson;
    }

    /**
     * Serialize the given Java object into JSON string.
     *
     * @param obj Object
     * @return String representation of the JSON
     */
    public static String serialize(Object obj) {
        return gson.toJson(obj);
    }

    /**
     * Deserialize the given JSON string to Java object.
     *
     * @param <T>        Type
     * @param body       The JSON string
     * @param returnType The type to deserialize into
     * @return The deserialized Java object
     */
    @SuppressWarnings("unchecked")
    public static <T> T deserialize(String body, Type returnType) {
        try {
            if (isLenientOnJson) {
                JsonReader jsonReader = new JsonReader(new StringReader(body));
                // see https://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/stream/JsonReader.html#setLenient(boolean)
                jsonReader.setLenient(true);
                return gson.fromJson(jsonReader, returnType);
            } else {
                return gson.fromJson(body, returnType);
            }
        } catch (JsonParseException e) {
            // Fallback processing when failed to parse JSON form response body:
            // return the response body string directly for the String return type;
            if (returnType.equals(String.class)) {
                return (T) body;
            } else {
                throw (e);
            }
        }
    }

    /**
     * Gson TypeAdapter for Byte Array type
     */
    public static class ByteArrayAdapter extends TypeAdapter<byte[]> {

        @Override
        public void write(JsonWriter out, byte[] value) throws IOException {
            if (value == null) {
                out.nullValue();
            } else {
                out.value(ByteString.of(value).base64());
            }
        }

        @Override
        public byte[] read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String bytesAsBase64 = in.nextString();
                    ByteString byteString = ByteString.decodeBase64(bytesAsBase64);
                    return byteString.toByteArray();
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 OffsetDateTime type
     */
    public static class OffsetDateTimeTypeAdapter extends TypeAdapter<OffsetDateTime> {

        private DateTimeFormatter formatter;

        public OffsetDateTimeTypeAdapter() {
            this(DateTimeFormatter.ISO_OFFSET_DATE_TIME);
        }

        public OffsetDateTimeTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, OffsetDateTime date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public OffsetDateTime read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    if (date.endsWith("+0000")) {
                        date = date.substring(0, date.length()-5) + "Z";
                    }
                    return OffsetDateTime.parse(date, formatter);
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 LocalDate type
     */
    public static class LocalDateTypeAdapter extends TypeAdapter<LocalDate> {

        private DateTimeFormatter formatter;

        public LocalDateTypeAdapter() {
            this(DateTimeFormatter.ISO_LOCAL_DATE);
        }

        public LocalDateTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, LocalDate date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public LocalDate read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    return LocalDate.parse(date, formatter);
            }
        }
    }

    public static void setOffsetDateTimeFormat(DateTimeFormatter dateFormat) {
        offsetDateTimeTypeAdapter.setFormat(dateFormat);
    }

    public static void setLocalDateFormat(DateTimeFormatter dateFormat) {
        localDateTypeAdapter.setFormat(dateFormat);
    }

    /**
     * Gson TypeAdapter for java.sql.Date type
     * If the dateFormat is null, a simple "yyyy-MM-dd" format will be used
     * (more efficient than SimpleDateFormat).
     */
    public static class SqlDateTypeAdapter extends TypeAdapter<java.sql.Date> {

        private DateFormat dateFormat;

        public SqlDateTypeAdapter() {}

        public SqlDateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, java.sql.Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = date.toString();
                }
                out.value(value);
            }
        }

        @Override
        public java.sql.Date read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    try {
                        if (dateFormat != null) {
                            return new java.sql.Date(dateFormat.parse(date).getTime());
                        }
                        return new java.sql.Date(ISO8601Utils.parse(date, new ParsePosition(0)).getTime());
                    } catch (ParseException e) {
                        throw new JsonParseException(e);
                    }
            }
        }
    }

    /**
     * Gson TypeAdapter for java.util.Date type
     * If the dateFormat is null, ISO8601Utils will be used.
     */
    public static class DateTypeAdapter extends TypeAdapter<Date> {

        private DateFormat dateFormat;

        public DateTypeAdapter() {}

        public DateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = ISO8601Utils.format(date, true);
                }
                out.value(value);
            }
        }

        @Override
        public Date read(JsonReader in) throws IOException {
            try {
                switch (in.peek()) {
                    case NULL:
                        in.nextNull();
                        return null;
                    default:
                        String date = in.nextString();
                        try {
                            if (dateFormat != null) {
                                return dateFormat.parse(date);
                            }
                            return ISO8601Utils.parse(date, new ParsePosition(0));
                        } catch (ParseException e) {
                            throw new JsonParseException(e);
                        }
                }
            } catch (IllegalArgumentException e) {
                throw new JsonParseException(e);
            }
        }
    }

    public static void setDateFormat(DateFormat dateFormat) {
        dateTypeAdapter.setFormat(dateFormat);
    }

    public static void setSqlDateFormat(DateFormat dateFormat) {
        sqlDateTypeAdapter.setFormat(dateFormat);
    }
}
