/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * OpenAPI spec version: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.clientapi.forgejo.model;

import java.util.Objects;
import com.clientapi.forgejo.model.Comment;
import com.clientapi.forgejo.model.Repository;
import com.clientapi.forgejo.model.User;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;


/**
 * Activity
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2023-10-14T16:18:05.057+02:00")
public class Activity   {
  @SerializedName("act_user")
  private User actUser = null;

  @SerializedName("act_user_id")
  private Long actUserId = null;

  @SerializedName("comment")
  private Comment comment = null;

  @SerializedName("comment_id")
  private Long commentId = null;

  @SerializedName("content")
  private String content = null;

  @SerializedName("created")
  private DateTime created = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("is_private")
  private Boolean isPrivate = null;

  @SerializedName("op_type")
  private String opType = null;

  @SerializedName("ref_name")
  private String refName = null;

  @SerializedName("repo")
  private Repository repo = null;

  @SerializedName("repo_id")
  private Long repoId = null;

  @SerializedName("user_id")
  private Long userId = null;

  public Activity actUser(User actUser) {
    this.actUser = actUser;
    return this;
  }

   /**
   * Get actUser
   * @return actUser
  **/
  @ApiModelProperty(example = "null", value = "")
  public User getActUser() {
    return actUser;
  }

  public void setActUser(User actUser) {
    this.actUser = actUser;
  }

  public Activity actUserId(Long actUserId) {
    this.actUserId = actUserId;
    return this;
  }

   /**
   * Get actUserId
   * @return actUserId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getActUserId() {
    return actUserId;
  }

  public void setActUserId(Long actUserId) {
    this.actUserId = actUserId;
  }

  public Activity comment(Comment comment) {
    this.comment = comment;
    return this;
  }

   /**
   * Get comment
   * @return comment
  **/
  @ApiModelProperty(example = "null", value = "")
  public Comment getComment() {
    return comment;
  }

  public void setComment(Comment comment) {
    this.comment = comment;
  }

  public Activity commentId(Long commentId) {
    this.commentId = commentId;
    return this;
  }

   /**
   * Get commentId
   * @return commentId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getCommentId() {
    return commentId;
  }

  public void setCommentId(Long commentId) {
    this.commentId = commentId;
  }

  public Activity content(String content) {
    this.content = content;
    return this;
  }

   /**
   * Get content
   * @return content
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getContent() {
    return content;
  }

  public void setContent(String content) {
    this.content = content;
  }

  public Activity created(DateTime created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getCreated() {
    return created;
  }

  public void setCreated(DateTime created) {
    this.created = created;
  }

  public Activity id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Activity isPrivate(Boolean isPrivate) {
    this.isPrivate = isPrivate;
    return this;
  }

   /**
   * Get isPrivate
   * @return isPrivate
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getIsPrivate() {
    return isPrivate;
  }

  public void setIsPrivate(Boolean isPrivate) {
    this.isPrivate = isPrivate;
  }

  public Activity opType(String opType) {
    this.opType = opType;
    return this;
  }

   /**
   * Get opType
   * @return opType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getOpType() {
    return opType;
  }

  public void setOpType(String opType) {
    this.opType = opType;
  }

  public Activity refName(String refName) {
    this.refName = refName;
    return this;
  }

   /**
   * Get refName
   * @return refName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRefName() {
    return refName;
  }

  public void setRefName(String refName) {
    this.refName = refName;
  }

  public Activity repo(Repository repo) {
    this.repo = repo;
    return this;
  }

   /**
   * Get repo
   * @return repo
  **/
  @ApiModelProperty(example = "null", value = "")
  public Repository getRepo() {
    return repo;
  }

  public void setRepo(Repository repo) {
    this.repo = repo;
  }

  public Activity repoId(Long repoId) {
    this.repoId = repoId;
    return this;
  }

   /**
   * Get repoId
   * @return repoId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getRepoId() {
    return repoId;
  }

  public void setRepoId(Long repoId) {
    this.repoId = repoId;
  }

  public Activity userId(Long userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getUserId() {
    return userId;
  }

  public void setUserId(Long userId) {
    this.userId = userId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Activity activity = (Activity) o;
    return Objects.equals(this.actUser, activity.actUser) &&
        Objects.equals(this.actUserId, activity.actUserId) &&
        Objects.equals(this.comment, activity.comment) &&
        Objects.equals(this.commentId, activity.commentId) &&
        Objects.equals(this.content, activity.content) &&
        Objects.equals(this.created, activity.created) &&
        Objects.equals(this.id, activity.id) &&
        Objects.equals(this.isPrivate, activity.isPrivate) &&
        Objects.equals(this.opType, activity.opType) &&
        Objects.equals(this.refName, activity.refName) &&
        Objects.equals(this.repo, activity.repo) &&
        Objects.equals(this.repoId, activity.repoId) &&
        Objects.equals(this.userId, activity.userId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(actUser, actUserId, comment, commentId, content, created, id, isPrivate, opType, refName, repo, repoId, userId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Activity {\n");
    
    sb.append("    actUser: ").append(toIndentedString(actUser)).append("\n");
    sb.append("    actUserId: ").append(toIndentedString(actUserId)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    commentId: ").append(toIndentedString(commentId)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    isPrivate: ").append(toIndentedString(isPrivate)).append("\n");
    sb.append("    opType: ").append(toIndentedString(opType)).append("\n");
    sb.append("    refName: ").append(toIndentedString(refName)).append("\n");
    sb.append("    repo: ").append(toIndentedString(repo)).append("\n");
    sb.append("    repoId: ").append(toIndentedString(repoId)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

