/*
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.clientapi.forgejo.model;

import java.util.Objects;
import com.clientapi.forgejo.model.ChangeFileOperation;
import com.clientapi.forgejo.model.CommitDateOptions;
import com.clientapi.forgejo.model.Identity;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.clientapi.forgejo.invoker.JSON;

/**
 * ChangeFilesOptions options for creating, updating or deleting multiple files Note: &#x60;author&#x60; and &#x60;committer&#x60; are optional (if only one is given, it will be used for the other, otherwise the authenticated user will be used)
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-10-14T17:14:00.188014500+02:00[Europe/Budapest]")
public class ChangeFilesOptions {
  public static final String SERIALIZED_NAME_AUTHOR = "author";
  @SerializedName(SERIALIZED_NAME_AUTHOR)
  private Identity author;

  public static final String SERIALIZED_NAME_BRANCH = "branch";
  @SerializedName(SERIALIZED_NAME_BRANCH)
  private String branch;

  public static final String SERIALIZED_NAME_COMMITTER = "committer";
  @SerializedName(SERIALIZED_NAME_COMMITTER)
  private Identity committer;

  public static final String SERIALIZED_NAME_DATES = "dates";
  @SerializedName(SERIALIZED_NAME_DATES)
  private CommitDateOptions dates;

  public static final String SERIALIZED_NAME_FILES = "files";
  @SerializedName(SERIALIZED_NAME_FILES)
  private List<ChangeFileOperation> files = new ArrayList<>();

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  private String message;

  public static final String SERIALIZED_NAME_NEW_BRANCH = "new_branch";
  @SerializedName(SERIALIZED_NAME_NEW_BRANCH)
  private String newBranch;

  public static final String SERIALIZED_NAME_SIGNOFF = "signoff";
  @SerializedName(SERIALIZED_NAME_SIGNOFF)
  private Boolean signoff;

  public ChangeFilesOptions() {
  }

  public ChangeFilesOptions author(Identity author) {
    
    this.author = author;
    return this;
  }

   /**
   * Get author
   * @return author
  **/
  @javax.annotation.Nullable
  public Identity getAuthor() {
    return author;
  }


  public void setAuthor(Identity author) {
    this.author = author;
  }


  public ChangeFilesOptions branch(String branch) {
    
    this.branch = branch;
    return this;
  }

   /**
   * branch (optional) to base this file from. if not given, the default branch is used
   * @return branch
  **/
  @javax.annotation.Nullable
  public String getBranch() {
    return branch;
  }


  public void setBranch(String branch) {
    this.branch = branch;
  }


  public ChangeFilesOptions committer(Identity committer) {
    
    this.committer = committer;
    return this;
  }

   /**
   * Get committer
   * @return committer
  **/
  @javax.annotation.Nullable
  public Identity getCommitter() {
    return committer;
  }


  public void setCommitter(Identity committer) {
    this.committer = committer;
  }


  public ChangeFilesOptions dates(CommitDateOptions dates) {
    
    this.dates = dates;
    return this;
  }

   /**
   * Get dates
   * @return dates
  **/
  @javax.annotation.Nullable
  public CommitDateOptions getDates() {
    return dates;
  }


  public void setDates(CommitDateOptions dates) {
    this.dates = dates;
  }


  public ChangeFilesOptions files(List<ChangeFileOperation> files) {
    
    this.files = files;
    return this;
  }

  public ChangeFilesOptions addFilesItem(ChangeFileOperation filesItem) {
    if (this.files == null) {
      this.files = new ArrayList<>();
    }
    this.files.add(filesItem);
    return this;
  }

   /**
   * list of file operations
   * @return files
  **/
  @javax.annotation.Nonnull
  public List<ChangeFileOperation> getFiles() {
    return files;
  }


  public void setFiles(List<ChangeFileOperation> files) {
    this.files = files;
  }


  public ChangeFilesOptions message(String message) {
    
    this.message = message;
    return this;
  }

   /**
   * message (optional) for the commit of this file. if not supplied, a default message will be used
   * @return message
  **/
  @javax.annotation.Nullable
  public String getMessage() {
    return message;
  }


  public void setMessage(String message) {
    this.message = message;
  }


  public ChangeFilesOptions newBranch(String newBranch) {
    
    this.newBranch = newBranch;
    return this;
  }

   /**
   * new_branch (optional) will make a new branch from &#x60;branch&#x60; before creating the file
   * @return newBranch
  **/
  @javax.annotation.Nullable
  public String getNewBranch() {
    return newBranch;
  }


  public void setNewBranch(String newBranch) {
    this.newBranch = newBranch;
  }


  public ChangeFilesOptions signoff(Boolean signoff) {
    
    this.signoff = signoff;
    return this;
  }

   /**
   * Add a Signed-off-by trailer by the committer at the end of the commit log message.
   * @return signoff
  **/
  @javax.annotation.Nullable
  public Boolean getSignoff() {
    return signoff;
  }


  public void setSignoff(Boolean signoff) {
    this.signoff = signoff;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChangeFilesOptions changeFilesOptions = (ChangeFilesOptions) o;
    return Objects.equals(this.author, changeFilesOptions.author) &&
        Objects.equals(this.branch, changeFilesOptions.branch) &&
        Objects.equals(this.committer, changeFilesOptions.committer) &&
        Objects.equals(this.dates, changeFilesOptions.dates) &&
        Objects.equals(this.files, changeFilesOptions.files) &&
        Objects.equals(this.message, changeFilesOptions.message) &&
        Objects.equals(this.newBranch, changeFilesOptions.newBranch) &&
        Objects.equals(this.signoff, changeFilesOptions.signoff);
  }

  @Override
  public int hashCode() {
    return Objects.hash(author, branch, committer, dates, files, message, newBranch, signoff);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChangeFilesOptions {\n");
    sb.append("    author: ").append(toIndentedString(author)).append("\n");
    sb.append("    branch: ").append(toIndentedString(branch)).append("\n");
    sb.append("    committer: ").append(toIndentedString(committer)).append("\n");
    sb.append("    dates: ").append(toIndentedString(dates)).append("\n");
    sb.append("    files: ").append(toIndentedString(files)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    newBranch: ").append(toIndentedString(newBranch)).append("\n");
    sb.append("    signoff: ").append(toIndentedString(signoff)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("author");
    openapiFields.add("branch");
    openapiFields.add("committer");
    openapiFields.add("dates");
    openapiFields.add("files");
    openapiFields.add("message");
    openapiFields.add("new_branch");
    openapiFields.add("signoff");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("files");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to ChangeFilesOptions
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ChangeFilesOptions.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ChangeFilesOptions is not found in the empty JSON string", ChangeFilesOptions.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ChangeFilesOptions.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ChangeFilesOptions` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ChangeFilesOptions.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `author`
      if (jsonObj.get("author") != null && !jsonObj.get("author").isJsonNull()) {
        Identity.validateJsonElement(jsonObj.get("author"));
      }
      if ((jsonObj.get("branch") != null && !jsonObj.get("branch").isJsonNull()) && !jsonObj.get("branch").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `branch` to be a primitive type in the JSON string but got `%s`", jsonObj.get("branch").toString()));
      }
      // validate the optional field `committer`
      if (jsonObj.get("committer") != null && !jsonObj.get("committer").isJsonNull()) {
        Identity.validateJsonElement(jsonObj.get("committer"));
      }
      // validate the optional field `dates`
      if (jsonObj.get("dates") != null && !jsonObj.get("dates").isJsonNull()) {
        CommitDateOptions.validateJsonElement(jsonObj.get("dates"));
      }
      // ensure the json data is an array
      if (!jsonObj.get("files").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `files` to be an array in the JSON string but got `%s`", jsonObj.get("files").toString()));
      }

      JsonArray jsonArrayfiles = jsonObj.getAsJsonArray("files");
      // validate the required field `files` (array)
      for (int i = 0; i < jsonArrayfiles.size(); i++) {
        ChangeFileOperation.validateJsonElement(jsonArrayfiles.get(i));
      };
      if ((jsonObj.get("message") != null && !jsonObj.get("message").isJsonNull()) && !jsonObj.get("message").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `message` to be a primitive type in the JSON string but got `%s`", jsonObj.get("message").toString()));
      }
      if ((jsonObj.get("new_branch") != null && !jsonObj.get("new_branch").isJsonNull()) && !jsonObj.get("new_branch").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `new_branch` to be a primitive type in the JSON string but got `%s`", jsonObj.get("new_branch").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ChangeFilesOptions.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ChangeFilesOptions' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ChangeFilesOptions> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ChangeFilesOptions.class));

       return (TypeAdapter<T>) new TypeAdapter<ChangeFilesOptions>() {
           @Override
           public void write(JsonWriter out, ChangeFilesOptions value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ChangeFilesOptions read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ChangeFilesOptions given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ChangeFilesOptions
  * @throws IOException if the JSON string is invalid with respect to ChangeFilesOptions
  */
  public static ChangeFilesOptions fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ChangeFilesOptions.class);
  }

 /**
  * Convert an instance of ChangeFilesOptions to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

