/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * OpenAPI spec version: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.clientapi.forgejo.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * ChangeFileOperation for creating, updating or deleting a file
 */
@ApiModel(description = "ChangeFileOperation for creating, updating or deleting a file")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2023-10-14T16:18:05.057+02:00")
public class ChangeFileOperation   {
  @SerializedName("content")
  private String content = null;

  @SerializedName("from_path")
  private String fromPath = null;

  /**
   * indicates what to do with the file
   */
  public enum OperationEnum {
    @SerializedName("create")
    CREATE("create"),
    
    @SerializedName("update")
    UPDATE("update"),
    
    @SerializedName("delete")
    DELETE("delete");

    private String value;

    OperationEnum(String value) {
      this.value = value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
  }

  @SerializedName("operation")
  private OperationEnum operation = null;

  @SerializedName("path")
  private String path = null;

  @SerializedName("sha")
  private String sha = null;

  public ChangeFileOperation content(String content) {
    this.content = content;
    return this;
  }

   /**
   * new or updated file content, must be base64 encoded
   * @return content
  **/
  @ApiModelProperty(example = "null", value = "new or updated file content, must be base64 encoded")
  public String getContent() {
    return content;
  }

  public void setContent(String content) {
    this.content = content;
  }

  public ChangeFileOperation fromPath(String fromPath) {
    this.fromPath = fromPath;
    return this;
  }

   /**
   * old path of the file to move
   * @return fromPath
  **/
  @ApiModelProperty(example = "null", value = "old path of the file to move")
  public String getFromPath() {
    return fromPath;
  }

  public void setFromPath(String fromPath) {
    this.fromPath = fromPath;
  }

  public ChangeFileOperation operation(OperationEnum operation) {
    this.operation = operation;
    return this;
  }

   /**
   * indicates what to do with the file
   * @return operation
  **/
  @ApiModelProperty(example = "null", required = true, value = "indicates what to do with the file")
  public OperationEnum getOperation() {
    return operation;
  }

  public void setOperation(OperationEnum operation) {
    this.operation = operation;
  }

  public ChangeFileOperation path(String path) {
    this.path = path;
    return this;
  }

   /**
   * path to the existing or new file
   * @return path
  **/
  @ApiModelProperty(example = "null", required = true, value = "path to the existing or new file")
  public String getPath() {
    return path;
  }

  public void setPath(String path) {
    this.path = path;
  }

  public ChangeFileOperation sha(String sha) {
    this.sha = sha;
    return this;
  }

   /**
   * sha is the SHA for the file that already exists, required for update or delete
   * @return sha
  **/
  @ApiModelProperty(example = "null", value = "sha is the SHA for the file that already exists, required for update or delete")
  public String getSha() {
    return sha;
  }

  public void setSha(String sha) {
    this.sha = sha;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChangeFileOperation changeFileOperation = (ChangeFileOperation) o;
    return Objects.equals(this.content, changeFileOperation.content) &&
        Objects.equals(this.fromPath, changeFileOperation.fromPath) &&
        Objects.equals(this.operation, changeFileOperation.operation) &&
        Objects.equals(this.path, changeFileOperation.path) &&
        Objects.equals(this.sha, changeFileOperation.sha);
  }

  @Override
  public int hashCode() {
    return Objects.hash(content, fromPath, operation, path, sha);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChangeFileOperation {\n");
    
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    fromPath: ").append(toIndentedString(fromPath)).append("\n");
    sb.append("    operation: ").append(toIndentedString(operation)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    sha: ").append(toIndentedString(sha)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

