/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * OpenAPI spec version: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.clientapi.forgejo.model;

import java.util.Objects;
import com.clientapi.forgejo.model.ContentsResponse;
import com.clientapi.forgejo.model.FileCommitResponse;
import com.clientapi.forgejo.model.PayloadCommitVerification;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * FilesResponse contains information about multiple files from a repo
 */
@ApiModel(description = "FilesResponse contains information about multiple files from a repo")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2023-10-14T16:18:05.057+02:00")
public class FilesResponse   {
  @SerializedName("commit")
  private FileCommitResponse commit = null;

  @SerializedName("files")
  private List<ContentsResponse> files = new ArrayList<ContentsResponse>();

  @SerializedName("verification")
  private PayloadCommitVerification verification = null;

  public FilesResponse commit(FileCommitResponse commit) {
    this.commit = commit;
    return this;
  }

   /**
   * Get commit
   * @return commit
  **/
  @ApiModelProperty(example = "null", value = "")
  public FileCommitResponse getCommit() {
    return commit;
  }

  public void setCommit(FileCommitResponse commit) {
    this.commit = commit;
  }

  public FilesResponse files(List<ContentsResponse> files) {
    this.files = files;
    return this;
  }

  public FilesResponse addFilesItem(ContentsResponse filesItem) {
    this.files.add(filesItem);
    return this;
  }

   /**
   * Get files
   * @return files
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<ContentsResponse> getFiles() {
    return files;
  }

  public void setFiles(List<ContentsResponse> files) {
    this.files = files;
  }

  public FilesResponse verification(PayloadCommitVerification verification) {
    this.verification = verification;
    return this;
  }

   /**
   * Get verification
   * @return verification
  **/
  @ApiModelProperty(example = "null", value = "")
  public PayloadCommitVerification getVerification() {
    return verification;
  }

  public void setVerification(PayloadCommitVerification verification) {
    this.verification = verification;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FilesResponse filesResponse = (FilesResponse) o;
    return Objects.equals(this.commit, filesResponse.commit) &&
        Objects.equals(this.files, filesResponse.files) &&
        Objects.equals(this.verification, filesResponse.verification);
  }

  @Override
  public int hashCode() {
    return Objects.hash(commit, files, verification);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FilesResponse {\n");
    
    sb.append("    commit: ").append(toIndentedString(commit)).append("\n");
    sb.append("    files: ").append(toIndentedString(files)).append("\n");
    sb.append("    verification: ").append(toIndentedString(verification)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

