/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * OpenAPI spec version: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.clientapi.forgejo.model;

import java.util.Objects;
import com.clientapi.forgejo.model.IssueConfigContactLink;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * IssueConfig
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2023-10-14T16:18:05.057+02:00")
public class IssueConfig   {
  @SerializedName("blank_issues_enabled")
  private Boolean blankIssuesEnabled = null;

  @SerializedName("contact_links")
  private List<IssueConfigContactLink> contactLinks = new ArrayList<IssueConfigContactLink>();

  public IssueConfig blankIssuesEnabled(Boolean blankIssuesEnabled) {
    this.blankIssuesEnabled = blankIssuesEnabled;
    return this;
  }

   /**
   * Get blankIssuesEnabled
   * @return blankIssuesEnabled
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getBlankIssuesEnabled() {
    return blankIssuesEnabled;
  }

  public void setBlankIssuesEnabled(Boolean blankIssuesEnabled) {
    this.blankIssuesEnabled = blankIssuesEnabled;
  }

  public IssueConfig contactLinks(List<IssueConfigContactLink> contactLinks) {
    this.contactLinks = contactLinks;
    return this;
  }

  public IssueConfig addContactLinksItem(IssueConfigContactLink contactLinksItem) {
    this.contactLinks.add(contactLinksItem);
    return this;
  }

   /**
   * Get contactLinks
   * @return contactLinks
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<IssueConfigContactLink> getContactLinks() {
    return contactLinks;
  }

  public void setContactLinks(List<IssueConfigContactLink> contactLinks) {
    this.contactLinks = contactLinks;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IssueConfig issueConfig = (IssueConfig) o;
    return Objects.equals(this.blankIssuesEnabled, issueConfig.blankIssuesEnabled) &&
        Objects.equals(this.contactLinks, issueConfig.contactLinks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(blankIssuesEnabled, contactLinks);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IssueConfig {\n");
    
    sb.append("    blankIssuesEnabled: ").append(toIndentedString(blankIssuesEnabled)).append("\n");
    sb.append("    contactLinks: ").append(toIndentedString(contactLinks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

