/*
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.clientapi.forgejo.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.clientapi.forgejo.invoker.JSON;

/**
 * PullReviewRequestOptions are options to add or remove pull review requests
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-10-14T17:14:00.188014500+02:00[Europe/Budapest]")
public class PullReviewRequestOptions {
  public static final String SERIALIZED_NAME_REVIEWERS = "reviewers";
  @SerializedName(SERIALIZED_NAME_REVIEWERS)
  private List<String> reviewers;

  public static final String SERIALIZED_NAME_TEAM_REVIEWERS = "team_reviewers";
  @SerializedName(SERIALIZED_NAME_TEAM_REVIEWERS)
  private List<String> teamReviewers;

  public PullReviewRequestOptions() {
  }

  public PullReviewRequestOptions reviewers(List<String> reviewers) {
    
    this.reviewers = reviewers;
    return this;
  }

  public PullReviewRequestOptions addReviewersItem(String reviewersItem) {
    if (this.reviewers == null) {
      this.reviewers = new ArrayList<>();
    }
    this.reviewers.add(reviewersItem);
    return this;
  }

   /**
   * Get reviewers
   * @return reviewers
  **/
  @javax.annotation.Nullable
  public List<String> getReviewers() {
    return reviewers;
  }


  public void setReviewers(List<String> reviewers) {
    this.reviewers = reviewers;
  }


  public PullReviewRequestOptions teamReviewers(List<String> teamReviewers) {
    
    this.teamReviewers = teamReviewers;
    return this;
  }

  public PullReviewRequestOptions addTeamReviewersItem(String teamReviewersItem) {
    if (this.teamReviewers == null) {
      this.teamReviewers = new ArrayList<>();
    }
    this.teamReviewers.add(teamReviewersItem);
    return this;
  }

   /**
   * Get teamReviewers
   * @return teamReviewers
  **/
  @javax.annotation.Nullable
  public List<String> getTeamReviewers() {
    return teamReviewers;
  }


  public void setTeamReviewers(List<String> teamReviewers) {
    this.teamReviewers = teamReviewers;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PullReviewRequestOptions pullReviewRequestOptions = (PullReviewRequestOptions) o;
    return Objects.equals(this.reviewers, pullReviewRequestOptions.reviewers) &&
        Objects.equals(this.teamReviewers, pullReviewRequestOptions.teamReviewers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reviewers, teamReviewers);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PullReviewRequestOptions {\n");
    sb.append("    reviewers: ").append(toIndentedString(reviewers)).append("\n");
    sb.append("    teamReviewers: ").append(toIndentedString(teamReviewers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("reviewers");
    openapiFields.add("team_reviewers");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to PullReviewRequestOptions
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PullReviewRequestOptions.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PullReviewRequestOptions is not found in the empty JSON string", PullReviewRequestOptions.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PullReviewRequestOptions.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PullReviewRequestOptions` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("reviewers") != null && !jsonObj.get("reviewers").isJsonNull() && !jsonObj.get("reviewers").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `reviewers` to be an array in the JSON string but got `%s`", jsonObj.get("reviewers").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("team_reviewers") != null && !jsonObj.get("team_reviewers").isJsonNull() && !jsonObj.get("team_reviewers").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `team_reviewers` to be an array in the JSON string but got `%s`", jsonObj.get("team_reviewers").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PullReviewRequestOptions.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PullReviewRequestOptions' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PullReviewRequestOptions> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PullReviewRequestOptions.class));

       return (TypeAdapter<T>) new TypeAdapter<PullReviewRequestOptions>() {
           @Override
           public void write(JsonWriter out, PullReviewRequestOptions value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PullReviewRequestOptions read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PullReviewRequestOptions given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PullReviewRequestOptions
  * @throws IOException if the JSON string is invalid with respect to PullReviewRequestOptions
  */
  public static PullReviewRequestOptions fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PullReviewRequestOptions.class);
  }

 /**
  * Convert an instance of PullReviewRequestOptions to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

