/*
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.clientapi.forgejo.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateGPGKeyOption
 */
public class CreateGPGKeyOptionTest {
    private final CreateGPGKeyOption model = new CreateGPGKeyOption();

    /**
     * Model tests for CreateGPGKeyOption
     */
    @Test
    public void testCreateGPGKeyOption() {
        // TODO: test CreateGPGKeyOption
    }

    /**
     * Test the property 'armoredPublicKey'
     */
    @Test
    public void armoredPublicKeyTest() {
        // TODO: test armoredPublicKey
    }

    /**
     * Test the property 'armoredSignature'
     */
    @Test
    public void armoredSignatureTest() {
        // TODO: test armoredSignature
    }

}
