/*
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.clientapi.forgejo.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DismissPullReviewOptions
 */
public class DismissPullReviewOptionsTest {
    private final DismissPullReviewOptions model = new DismissPullReviewOptions();

    /**
     * Model tests for DismissPullReviewOptions
     */
    @Test
    public void testDismissPullReviewOptions() {
        // TODO: test DismissPullReviewOptions
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'priors'
     */
    @Test
    public void priorsTest() {
        // TODO: test priors
    }

}
