/*
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.clientapi.forgejo.model;

import com.clientapi.forgejo.model.FileCommitResponse;
import com.clientapi.forgejo.model.PayloadCommitVerification;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FileDeleteResponse
 */
public class FileDeleteResponseTest {
    private final FileDeleteResponse model = new FileDeleteResponse();

    /**
     * Model tests for FileDeleteResponse
     */
    @Test
    public void testFileDeleteResponse() {
        // TODO: test FileDeleteResponse
    }

    /**
     * Test the property 'commit'
     */
    @Test
    public void commitTest() {
        // TODO: test commit
    }

    /**
     * Test the property 'content'
     */
    @Test
    public void contentTest() {
        // TODO: test content
    }

    /**
     * Test the property 'verification'
     */
    @Test
    public void verificationTest() {
        // TODO: test verification
    }

}
