/*
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.clientapi.forgejo.model;

import com.clientapi.forgejo.model.ContentsResponse;
import com.clientapi.forgejo.model.FileCommitResponse;
import com.clientapi.forgejo.model.PayloadCommitVerification;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FilesResponse
 */
public class FilesResponseTest {
    private final FilesResponse model = new FilesResponse();

    /**
     * Model tests for FilesResponse
     */
    @Test
    public void testFilesResponse() {
        // TODO: test FilesResponse
    }

    /**
     * Test the property 'commit'
     */
    @Test
    public void commitTest() {
        // TODO: test commit
    }

    /**
     * Test the property 'files'
     */
    @Test
    public void filesTest() {
        // TODO: test files
    }

    /**
     * Test the property 'verification'
     */
    @Test
    public void verificationTest() {
        // TODO: test verification
    }

}
