/*
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.clientapi.forgejo.model;

import com.clientapi.forgejo.model.IssueConfigContactLink;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for IssueConfig
 */
public class IssueConfigTest {
    private final IssueConfig model = new IssueConfig();

    /**
     * Model tests for IssueConfig
     */
    @Test
    public void testIssueConfig() {
        // TODO: test IssueConfig
    }

    /**
     * Test the property 'blankIssuesEnabled'
     */
    @Test
    public void blankIssuesEnabledTest() {
        // TODO: test blankIssuesEnabled
    }

    /**
     * Test the property 'contactLinks'
     */
    @Test
    public void contactLinksTest() {
        // TODO: test contactLinks
    }

}
