/*
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.clientapi.forgejo.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for NodeInfoServices
 */
public class NodeInfoServicesTest {
    private final NodeInfoServices model = new NodeInfoServices();

    /**
     * Model tests for NodeInfoServices
     */
    @Test
    public void testNodeInfoServices() {
        // TODO: test NodeInfoServices
    }

    /**
     * Test the property 'inbound'
     */
    @Test
    public void inboundTest() {
        // TODO: test inbound
    }

    /**
     * Test the property 'outbound'
     */
    @Test
    public void outboundTest() {
        // TODO: test outbound
    }

}
