/*
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.clientapi.forgejo.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PullReviewRequestOptions
 */
public class PullReviewRequestOptionsTest {
    private final PullReviewRequestOptions model = new PullReviewRequestOptions();

    /**
     * Model tests for PullReviewRequestOptions
     */
    @Test
    public void testPullReviewRequestOptions() {
        // TODO: test PullReviewRequestOptions
    }

    /**
     * Test the property 'reviewers'
     */
    @Test
    public void reviewersTest() {
        // TODO: test reviewers
    }

    /**
     * Test the property 'teamReviewers'
     */
    @Test
    public void teamReviewersTest() {
        // TODO: test teamReviewers
    }

}
