/*
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.clientapi.forgejo.model;

import com.clientapi.forgejo.model.Team;
import com.clientapi.forgejo.model.User;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RepoTransfer
 */
public class RepoTransferTest {
    private final RepoTransfer model = new RepoTransfer();

    /**
     * Model tests for RepoTransfer
     */
    @Test
    public void testRepoTransfer() {
        // TODO: test RepoTransfer
    }

    /**
     * Test the property 'doer'
     */
    @Test
    public void doerTest() {
        // TODO: test doer
    }

    /**
     * Test the property 'recipient'
     */
    @Test
    public void recipientTest() {
        // TODO: test recipient
    }

    /**
     * Test the property 'teams'
     */
    @Test
    public void teamsTest() {
        // TODO: test teams
    }

}
