/*
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.clientapi.forgejo.model;

import com.clientapi.forgejo.model.Comment;
import com.clientapi.forgejo.model.Issue;
import com.clientapi.forgejo.model.Label;
import com.clientapi.forgejo.model.Milestone;
import com.clientapi.forgejo.model.Team;
import com.clientapi.forgejo.model.TrackedTime;
import com.clientapi.forgejo.model.User;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TimelineComment
 */
public class TimelineCommentTest {
    private final TimelineComment model = new TimelineComment();

    /**
     * Model tests for TimelineComment
     */
    @Test
    public void testTimelineComment() {
        // TODO: test TimelineComment
    }

    /**
     * Test the property 'assignee'
     */
    @Test
    public void assigneeTest() {
        // TODO: test assignee
    }

    /**
     * Test the property 'assigneeTeam'
     */
    @Test
    public void assigneeTeamTest() {
        // TODO: test assigneeTeam
    }

    /**
     * Test the property 'body'
     */
    @Test
    public void bodyTest() {
        // TODO: test body
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'dependentIssue'
     */
    @Test
    public void dependentIssueTest() {
        // TODO: test dependentIssue
    }

    /**
     * Test the property 'htmlUrl'
     */
    @Test
    public void htmlUrlTest() {
        // TODO: test htmlUrl
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'issueUrl'
     */
    @Test
    public void issueUrlTest() {
        // TODO: test issueUrl
    }

    /**
     * Test the property 'label'
     */
    @Test
    public void labelTest() {
        // TODO: test label
    }

    /**
     * Test the property 'milestone'
     */
    @Test
    public void milestoneTest() {
        // TODO: test milestone
    }

    /**
     * Test the property 'newRef'
     */
    @Test
    public void newRefTest() {
        // TODO: test newRef
    }

    /**
     * Test the property 'newTitle'
     */
    @Test
    public void newTitleTest() {
        // TODO: test newTitle
    }

    /**
     * Test the property 'oldMilestone'
     */
    @Test
    public void oldMilestoneTest() {
        // TODO: test oldMilestone
    }

    /**
     * Test the property 'oldProjectId'
     */
    @Test
    public void oldProjectIdTest() {
        // TODO: test oldProjectId
    }

    /**
     * Test the property 'oldRef'
     */
    @Test
    public void oldRefTest() {
        // TODO: test oldRef
    }

    /**
     * Test the property 'oldTitle'
     */
    @Test
    public void oldTitleTest() {
        // TODO: test oldTitle
    }

    /**
     * Test the property 'projectId'
     */
    @Test
    public void projectIdTest() {
        // TODO: test projectId
    }

    /**
     * Test the property 'pullRequestUrl'
     */
    @Test
    public void pullRequestUrlTest() {
        // TODO: test pullRequestUrl
    }

    /**
     * Test the property 'refAction'
     */
    @Test
    public void refActionTest() {
        // TODO: test refAction
    }

    /**
     * Test the property 'refComment'
     */
    @Test
    public void refCommentTest() {
        // TODO: test refComment
    }

    /**
     * Test the property 'refCommitSha'
     */
    @Test
    public void refCommitShaTest() {
        // TODO: test refCommitSha
    }

    /**
     * Test the property 'refIssue'
     */
    @Test
    public void refIssueTest() {
        // TODO: test refIssue
    }

    /**
     * Test the property 'removedAssignee'
     */
    @Test
    public void removedAssigneeTest() {
        // TODO: test removedAssignee
    }

    /**
     * Test the property 'resolveDoer'
     */
    @Test
    public void resolveDoerTest() {
        // TODO: test resolveDoer
    }

    /**
     * Test the property 'reviewId'
     */
    @Test
    public void reviewIdTest() {
        // TODO: test reviewId
    }

    /**
     * Test the property 'trackedTime'
     */
    @Test
    public void trackedTimeTest() {
        // TODO: test trackedTime
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'user'
     */
    @Test
    public void userTest() {
        // TODO: test user
    }

}
