/*
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * The version of the OpenAPI document: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.clientapi.forgejo.api;

import com.clientapi.forgejo.invoker.ApiException;
import com.clientapi.forgejo.model.CreateHookOption;
import com.clientapi.forgejo.model.CreateKeyOption;
import com.clientapi.forgejo.model.CreateOrgOption;
import com.clientapi.forgejo.model.CreateRepoOption;
import com.clientapi.forgejo.model.CreateUserOption;
import com.clientapi.forgejo.model.Cron;
import com.clientapi.forgejo.model.EditHookOption;
import com.clientapi.forgejo.model.EditUserOption;
import com.clientapi.forgejo.model.Email;
import com.clientapi.forgejo.model.Hook;
import com.clientapi.forgejo.model.Organization;
import com.clientapi.forgejo.model.PublicKey;
import com.clientapi.forgejo.model.RenameUserOption;
import com.clientapi.forgejo.model.Repository;
import com.clientapi.forgejo.model.User;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AdminApi
 */
@Disabled
public class AdminApiTest {

    private final AdminApi api = new AdminApi();

    /**
     * Adopt unadopted files as a repository
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void adminAdoptRepositoryTest() throws ApiException {
        String owner = null;
        String repo = null;
        api.adminAdoptRepository(owner, repo);
        // TODO: test validations
    }

    /**
     * Create a hook
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void adminCreateHookTest() throws ApiException {
        CreateHookOption body = null;
        Hook response = api.adminCreateHook(body);
        // TODO: test validations
    }

    /**
     * Create an organization
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void adminCreateOrgTest() throws ApiException {
        String username = null;
        CreateOrgOption organization = null;
        Organization response = api.adminCreateOrg(username, organization);
        // TODO: test validations
    }

    /**
     * Add a public key on behalf of a user
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void adminCreatePublicKeyTest() throws ApiException {
        String username = null;
        CreateKeyOption key = null;
        PublicKey response = api.adminCreatePublicKey(username, key);
        // TODO: test validations
    }

    /**
     * Create a repository on behalf of a user
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void adminCreateRepoTest() throws ApiException {
        String username = null;
        CreateRepoOption repository = null;
        Repository response = api.adminCreateRepo(username, repository);
        // TODO: test validations
    }

    /**
     * Create a user
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void adminCreateUserTest() throws ApiException {
        CreateUserOption body = null;
        User response = api.adminCreateUser(body);
        // TODO: test validations
    }

    /**
     * List cron tasks
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void adminCronListTest() throws ApiException {
        Integer page = null;
        Integer limit = null;
        List<Cron> response = api.adminCronList(page, limit);
        // TODO: test validations
    }

    /**
     * Run cron task
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void adminCronRunTest() throws ApiException {
        String task = null;
        api.adminCronRun(task);
        // TODO: test validations
    }

    /**
     * Delete a hook
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void adminDeleteHookTest() throws ApiException {
        Long id = null;
        api.adminDeleteHook(id);
        // TODO: test validations
    }

    /**
     * Delete unadopted files
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void adminDeleteUnadoptedRepositoryTest() throws ApiException {
        String owner = null;
        String repo = null;
        api.adminDeleteUnadoptedRepository(owner, repo);
        // TODO: test validations
    }

    /**
     * Delete a user
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void adminDeleteUserTest() throws ApiException {
        String username = null;
        Boolean purge = null;
        api.adminDeleteUser(username, purge);
        // TODO: test validations
    }

    /**
     * Delete a user&#39;s public key
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void adminDeleteUserPublicKeyTest() throws ApiException {
        String username = null;
        Long id = null;
        api.adminDeleteUserPublicKey(username, id);
        // TODO: test validations
    }

    /**
     * Update a hook
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void adminEditHookTest() throws ApiException {
        Long id = null;
        EditHookOption body = null;
        Hook response = api.adminEditHook(id, body);
        // TODO: test validations
    }

    /**
     * Edit an existing user
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void adminEditUserTest() throws ApiException {
        String username = null;
        EditUserOption body = null;
        User response = api.adminEditUser(username, body);
        // TODO: test validations
    }

    /**
     * List all emails
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void adminGetAllEmailsTest() throws ApiException {
        Integer page = null;
        Integer limit = null;
        List<Email> response = api.adminGetAllEmails(page, limit);
        // TODO: test validations
    }

    /**
     * List all organizations
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void adminGetAllOrgsTest() throws ApiException {
        Integer page = null;
        Integer limit = null;
        List<Organization> response = api.adminGetAllOrgs(page, limit);
        // TODO: test validations
    }

    /**
     * Get a hook
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void adminGetHookTest() throws ApiException {
        Long id = null;
        Hook response = api.adminGetHook(id);
        // TODO: test validations
    }

    /**
     * List system&#39;s webhooks
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void adminListHooksTest() throws ApiException {
        Integer page = null;
        Integer limit = null;
        List<Hook> response = api.adminListHooks(page, limit);
        // TODO: test validations
    }

    /**
     * Rename a user
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void adminRenameUserTest() throws ApiException {
        String username = null;
        RenameUserOption body = null;
        api.adminRenameUser(username, body);
        // TODO: test validations
    }

    /**
     * Search all emails
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void adminSearchEmailsTest() throws ApiException {
        String q = null;
        Integer page = null;
        Integer limit = null;
        List<Email> response = api.adminSearchEmails(q, page, limit);
        // TODO: test validations
    }

    /**
     * Search users according filter conditions
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void adminSearchUsersTest() throws ApiException {
        Long sourceId = null;
        String loginName = null;
        Integer page = null;
        Integer limit = null;
        List<User> response = api.adminSearchUsers(sourceId, loginName, page, limit);
        // TODO: test validations
    }

    /**
     * List unadopted repositories
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void adminUnadoptedListTest() throws ApiException {
        Integer page = null;
        Integer limit = null;
        String pattern = null;
        List<String> response = api.adminUnadoptedList(page, limit, pattern);
        // TODO: test validations
    }

}
