/**
 * Forgejo API.
 * This documentation describes the Forgejo API.
 *
 * OpenAPI spec version: 1.20.5+0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.clientapi.forgejo.api;

import com.clientapi.forgejo.invoker.ApiException;
import com.clientapi.forgejo.model.GitignoreTemplateInfo;
import com.clientapi.forgejo.model.LabelTemplate;
import com.clientapi.forgejo.model.LicenseTemplateInfo;
import com.clientapi.forgejo.model.NodeInfo;
import com.clientapi.forgejo.model.ServerVersion;
import com.clientapi.forgejo.model.LicensesTemplateListEntry;
import com.clientapi.forgejo.model.MarkdownOption;
import com.clientapi.forgejo.model.MarkupOption;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MiscellaneousApi
 */
public class MiscellaneousApiTest {

    private final MiscellaneousApi api = new MiscellaneousApi();

    
    /**
     * Returns information about a gitignore template
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getGitignoreTemplateInfoTest() throws ApiException {
        String name = null;
        // GitignoreTemplateInfo response = api.getGitignoreTemplateInfo(name);

        // TODO: test validations
    }
    
    /**
     * Returns all labels in a template
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getLabelTemplateInfoTest() throws ApiException {
        String name = null;
        // List<LabelTemplate> response = api.getLabelTemplateInfo(name);

        // TODO: test validations
    }
    
    /**
     * Returns information about a license template
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getLicenseTemplateInfoTest() throws ApiException {
        String name = null;
        // LicenseTemplateInfo response = api.getLicenseTemplateInfo(name);

        // TODO: test validations
    }
    
    /**
     * Returns the nodeinfo of the Gitea application
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getNodeInfoTest() throws ApiException {
        // NodeInfo response = api.getNodeInfo();

        // TODO: test validations
    }
    
    /**
     * Get default signing-key.gpg
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSigningKeyTest() throws ApiException {
        // String response = api.getSigningKey();

        // TODO: test validations
    }
    
    /**
     * Returns the version of the Gitea application
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getVersionTest() throws ApiException {
        // ServerVersion response = api.getVersion();

        // TODO: test validations
    }
    
    /**
     * Returns a list of all gitignore templates
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listGitignoresTemplatesTest() throws ApiException {
        // List<String> response = api.listGitignoresTemplates();

        // TODO: test validations
    }
    
    /**
     * Returns a list of all label templates
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listLabelTemplatesTest() throws ApiException {
        // List<String> response = api.listLabelTemplates();

        // TODO: test validations
    }
    
    /**
     * Returns a list of all license templates
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listLicenseTemplatesTest() throws ApiException {
        // List<LicensesTemplateListEntry> response = api.listLicenseTemplates();

        // TODO: test validations
    }
    
    /**
     * Render a markdown document as HTML
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void renderMarkdownTest() throws ApiException {
        MarkdownOption body = null;
        // String response = api.renderMarkdown(body);

        // TODO: test validations
    }
    
    /**
     * Render raw markdown as HTML
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void renderMarkdownRawTest() throws ApiException {
        String body = null;
        // String response = api.renderMarkdownRaw(body);

        // TODO: test validations
    }
    
    /**
     * Render a markup document as HTML
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void renderMarkupTest() throws ApiException {
        MarkupOption body = null;
        // String response = api.renderMarkup(body);

        // TODO: test validations
    }
    
}
